apiVersion: apps/v1

kind: Deployment

metadata:
  name: flask-deployment
  labels:
    app: flask-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-pod

  template:
    metadata:
      name: flask-pod
      labels:
        app: flask-pod

    spec:
      containers:
        - name: ml-flask-container
          image: mlapi
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
